# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-16 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_feature', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item_feature',
            new_name='Item',
        ),
    ]
